name: 问题报告
description: 报告本站点相关的问题。请认真阅读并填写，否则 issue 将可能被直接关闭。
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        这里是 TiamatXu 的个人文档仓库，仅处理：
        1. 文档错误；
        2. 网站文件缺失（地址指向不存在的文件）；
        3. 其他与本仓库相关问题。

  - type: checkboxes
    id: terms
    attributes:
      label: 提问须知
      description: 请认真阅读以上说明后，勾选以下字段。
      options:
        - label: 我强制刷新过页面，确定这是网站的问题，而不是缓存问题。
          required: true

  - type: dropdown
    id: issuetype
    attributes:
      label: 问题类型
      description: 请选择本 issue 所涉及的问题类型。
      options:
        - 文档错误
        - 文件缺失
        - 链接失效
        - 其他
    validations:
      required: true

  - type: textarea
    id: desc
    attributes:
      label: 问题描述
      description: 请描述问题，**截图+有效链接更佳**。
    validations:
      required: true

