- text: BashBuilder
  activeMatch: ^/(bash-builder)/
  link: /bash-builder/index
- text: 备忘录
  activeMatch: ^/(memo|linux|windows-os-bug|doc-site|todo|showcase)/
  items:
    - text: 全栈八股文
      link: /memo/introduction
    - text: Linux
      link: /linux/zookeeper-docker-arrangement
    - text: Windows OS Bug
      link: /windows-os-bug/bug
#    - text: 文档型网站构建指南
#      link: /doc-site/vitepress-deployment-guide
#    - text: TODO
#      link: /todo/todolists
#    - text: Showcase
#      link: /showcase/icons
- text: AI 专栏
  activeMatch: ^/(AI)/
  items:
    - text: RAG (检索增强生成)
      link: /AI/RAG/introduction
    - text: AI 应用核心知识
      link: /AI/core-knowledge/index
    - text: AI Coding Guide
      link: /AI/coding/claude-code-guide
#    - text: 大模型
#      link: /AI/large-model/index
- text: 项目
  activeMatch: ^/project/
  items:
    - text: Github
      items:
        - text: Personal HomePage
          link: https://github.com/TiamatXu
        - text: This Site Repo
          link: https://github.com/TiamatXu/TiamatXu.github.io
    - text: 开发项目
      items:
        - text: 空列表
          link: /null
    - text: 其他
      items:
        - text: Github 热力图组件
          link: /project/contribution-graph
- text: 关于
  activeMatch: ^/about/
  items:
    - text: 关于本站
      link: /about/website
    - text: 关于作者
      link: /about/author
